# Numpy Arrays

In [4]:
import numpy as np

In [5]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
lista = [1,2,3,4,5]

In [11]:
array = np.array(lista)

In [12]:
array+20

array([21, 22, 23, 24, 25])

In [14]:
array*2

array([ 2,  4,  6,  8, 10])

In [15]:
array**2

array([ 1,  4,  9, 16, 25])

In [17]:
np.sqrt(lista)#raiz quadrada

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [ ]:
#np.ceil()#arrendo para baixo

In [ ]:
#np.floor() arrendoda para cima

In [ ]:
#np.around(nomelista,2)casa decimal 

# Numpy Array (Operações Inteligentes)

In [ ]:
#quando faz uma fatiamento o ultimo elemento não entra

# Numpy Array (Indexando e Cortando _'Slicing'_)

# Numpy Array (Multiplas Dimensões)

# Numpy Array e Boolean

# Numpy e Números Aleatórios